# Render Blueprint - https://render.com/docs/blueprint-spec
services:
  - type: web
    name: supervision-segments
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
